version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'

  backend:
    platform: linux/x86_64
    build:
      context: backend
    volumes:
      - ./backend:/usr/src/app
      - ./backend/vendor/bundle:/usr/vendor/bundle
    ports:
      - '8080:8080'
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_PORT: 3306
      DB_HOST: db
      RAILS_MAX_THREADS: 5
      RAILS_ENV: development

  frontend:
    platform: linux/x86_64
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'